version: "3.9"
name: "docker-containers-in-vs"

services:
  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    container_name: users-api
    build:
      context: .
      dockerfile: Users.Api/Dockerfile
    ports:
      - 3001:80
      - 3101:443
    networks:
      - network-backend

  roles.api:
    image: ${DOCKER_REGISTRY-}rolesapi
    container_name: roles-api
    build:
      context: .
      dockerfile: Roles.Api/Dockerfile
    ports:
      - 4001:80
      - 4101:443
    networks:
      - network-backend

networks:
  network-backend:
    name: network-backend
    driver: bridge
